eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
spring:
  application:
    name: admin-server
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456