spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
     defaultZone: http://user:123456@localhost:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: debug